name: Deploy verification pages

on:
  push:
    branches: [ main ]
    paths:
      - 'verify/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build site (to verify/dist)
        working-directory: verify/scripts
        run: |
          python3 generate_verifications.py --out ../dist --clean

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: verify/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
